"""Read bounded native metadata without hydrating the canonical JSON document."""

from dataclasses import dataclass

from sqlalchemy import Text, case, func, select
from sqlalchemy import cast as sql_cast
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Session

from mnemonic_api.transcript_normalized_storage import SEGMENTS
from mnemonic_api.transcript_read_schemas import SegmentRead

OPTIONAL_METADATA_BYTES = 4096
NATIVE_FIELDS = (
    "role", "timestamp", "native_event_id", "native_parent_id", "native_branch_id",
    "channel", "tool_name", "call_id",
)
# These fields are generated by the adapter, not copied from native metadata.
ESSENTIAL_FIELDS = (
    "segment_id", "event_id", "ordinal", "source_record", "source_block", "content_kind",
    "is_sidechain", "is_error", "dispositions", "related_segment_id",
)


def _object(fields: tuple[str, ...]):
    arguments = [part for name in fields for part in (name, SEGMENTS.c.segment_data[name])]
    return func.jsonb_build_object(*arguments)


@dataclass(frozen=True)
class SegmentProjection:
    item: SegmentRead
    remaining: int
    metadata_remaining: int


def read_segment(database: Session, scope, ordinal: int, start: int, budget: int,
                 metadata_budget: int) -> SegmentProjection:
    optional = func.jsonb_strip_nulls(_object(NATIVE_FIELDS))
    optional_bytes = func.octet_length(sql_cast(optional, Text))
    # PostgreSQL evaluates the size before returning the optional projection. A
    # large native identifier/tool name never crosses the database connection.
    row = database.execute(select(
        _object(ESSENTIAL_FIELDS).label("essential"),
        case((optional_bytes <= metadata_budget, optional), else_=sql_cast({}, JSONB))
        .label("optional"), optional_bytes.label("optional_bytes"),
        func.length(SEGMENTS.c.text).label("length"),
        func.substr(SEGMENTS.c.text, start + 1, budget).label("fragment"),
        func.octet_length(sql_cast(SEGMENTS.c.segment_data["payload"], Text))
        .label("payload_bytes"),
    ).where(scope, SEGMENTS.c.ordinal == ordinal)).one()
    item = SegmentRead.model_validate(dict(row.essential, **row.optional,
        text=row.fragment, text_offset=start,
        text_truncated=row.length > start + len(row.fragment)))
    if row.optional_bytes > metadata_budget:
        item.dispositions.append("metadata_omitted_for_budget")
    else:
        metadata_budget -= row.optional_bytes
    remaining = budget - len(item.text)
    if row.payload_bytes is not None and row.payload_bytes <= remaining:
        item.payload = database.scalar(select(SEGMENTS.c.segment_data["payload"]).where(
            scope, SEGMENTS.c.ordinal == ordinal))
        remaining -= row.payload_bytes
    elif row.payload_bytes and row.payload_bytes > 4:
        item.dispositions.append("payload_omitted_for_budget")
    return SegmentProjection(item, remaining, metadata_budget)
